# 
#    |  |    \    _ \  _ \ \ \  /     \ |  __| \ \      /   \ \  /  __|    \    _ \   | 
#    __ |   _ \   __/  __/  \  /     .  |  _|   \ \ \  /     \  /   _|    _ \     /  _| 
#   _| _| _/  _\ _|   _|     _|     _|\_| ___|   \_/\_/       _|   ___| _/  _\ _|_\  _) 
# 
#  Developed by xSavior_of_God                                     
# 
#  For SUPPORT                                                      
#   <Discord/>     https://discord.gg/5UuVdTE                       
# 
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

# Set it to true to enable the plugin!
Enabled: false

# How often should I create a firework? ( /!\ in ticks -> 20 Ticks == 1 Second /!\ )
Timer: 200

# Check if there are more than X players in a Chunk, if so, STOP the event for new ones.
Limit: 5

# How many fireworks will spawn?
AmountPerPlayer: 5
# What effect can the firework have?
#   - BALL
#     A small ball effect
#   - BALL_LARGE
#     A large ball effect
#   - BURST
#     A burst effect
#   - CREEPER
#     A creeper-face effect
#   - STAR
#     A star-shaped effect
#   - RANDOM
#     A Random effect
FireworkEffectTypes:
  - 'RANDOM'

# Here you have to indicate the maximum distance at which a firework can be generated
RandomSpawnPosition:
  # Horizontal
  # Example:
  #     Horizontal 25 
  #   this means that I will generate a firework in a random position
  #   in Horizontal between -25 and 25 blocks from where the player is
  Horizontal: 25
  # Vertical
  # Example:
  #     Vertical: 25 
  #   this means that I will generate a firework in a random position
  #   in Vertical between -25 and 25 blocks + ExplosionHeight blocks 
  #   from where the player is
  Vertical: 25

# How many blocks in height will the firework have to explode relative
# to the player's position + Vertical?
ExplosionHeight: 50

# Do you want to be always night in the worlds where fireworks will spawn?
AlwaysNight:
  Enabled: false
  # If true, the time of the world will be based on that in real life
  # 
  #            /!\ !! Warning !! /!\
  # 
  # If you have a plugin that uses game time for something, 
  # that setting could break that plugin!
  UseRealTime: true
  # Below you can decide which worlds to apply this
  Worlds:
    # If true the indicated worlds will be in blacklist
    # If false the indicated worlds will be in whitelist
    Blacklist: false
    # List of names of the various worlds
    # Set to 'ALLWORLDS' to use all worlds! (NB: is cAsE sEnSiTiVe )
    List:
      - 'world'

# Here you can decide the worlds in which to generate the fireworks and the time. 
Worlds:
  # If true the indicated worlds will be in blacklist
  # If false the indicated worlds will be in whitelist
  Blacklist: false
  # Do you want the fires to be launched only at night?
  OnlyOnNight:
    Enabled: true
    InRealLife:
      # Do you want to rely on world time or real life time?
      Enabled: false
      # Available Time Zones https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      Timezone: "GMT+1"
    # Indicates the month number in which the plugin will have to work
    #  1 => January
    # -1 => to disable
    Month: -1
    # At what time does the night starts?
    Starts: "19:00"
    # At what time does the night ends?
    Ends: "5:30"
  # List of names of the various worlds
  # Set to 'ALLWORLDS' to use all worlds! (NB: is cAsE sEnSiTiVe )
  List:
    - 'world'