# 
#    |  |    \    _ \  _ \ \ \  /     \ |  __| \ \      /   \ \  /  __|    \    _ \   | 
#    __ |   _ \   __/  __/  \  /     .  |  _|   \ \ \  /     \  /   _|    _ \     /  _| 
#   _| _| _/  _\ _|   _|     _|     _|\_| ___|   \_/\_/       _|   ___| _/  _\ _|_\  _) 
# 
#  Developed by xSavior_of_God                                     
# 
#  For SUPPORT                                                      
#   <Discord/>     https://discord.gg/5UuVdTE
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

# Set it to true to enable the plugin!
Enabled: false

# What kind of animation for your fireworks do you like to use?
#   STANDARD           - Spawns multiple fireworks all at once
#   HOURLY             - Spawns multiple fireworks every hour all at once for a limited time (config: HourlyDuration)
#   STANDARD_REALISTIC - Spawns multiple fireworks randomly (More realistic)
#   HOURLY_REALISTIC   - Spawns multiple fireworks randomly (More realistic) for a limited time (config: HourlyDuration)
#
# Valid values: STANDARD, HOURLY, STANDARD_REALISTIC, HOURLY_REALISTIC
SpawnAnimationType: STANDARD

# Time in ticks (20 ticks == 1 second) -> 6000 ticks == 5 minutes
# only for HOURLY and HOURLY_LINEAR animations
HourlyDuration: 6000

# Timezone for the HOURLY and HOURLY_LINEAR animations
HourlyTimezone: "GMT+2"

# How often should I create a firework? ( /!\ in ticks -> 20 Ticks == 1 Second /!\ )
Timer: 60

# Check if there are more than X players in a Chunk, if so, STOP the event for new ones.
Limit: 5

# How many fireworks will spawn?
AmountPerPlayer: 5
# What effect can the firework have?
#   - BALL
#     A small ball effect
#   - BALL_LARGE
#     A large ball effect
#   - BURST
#     A burst effect
#   - CREEPER
#     A creeper-face effect
#   - STAR
#     A star-shaped effect
#   - RANDOM
#     A Random effect
FireworkEffectTypes:
  - 'RANDOM'

# Here you have to indicate the maximum distance at which a firework can be generated
RandomSpawnPosition:
  # Horizontal
  # Example:
  #     Horizontal 25 
  #   this means that I will generate a firework in a random position
  #   in Horizontal between -25 and 25 blocks from where the player is
  Horizontal: 25
  # Vertical
  # Example:
  #     Vertical: 25 
  #   this means that I will generate a firework in a random position
  #   in Vertical between -25 and 25 blocks + ExplosionHeight blocks 
  #   from where the player is
  Vertical: 25

# How many blocks in height will the firework have to explode relative
# to the player's position + Vertical?
ExplosionHeight: 40

# Here you can decide the worlds in which to generate the fireworks and the time. 
Worlds:
  # Do you want the fires to be launched only at night?
  OnlyOnNight:
    Enabled: true

  # Do you want to be always night in the worlds where fireworks will spawn?
  AlwaysNight:
    # /!\ If is Enabled, we suggest disabling the doDaylightCycle rule, as to further optimize the world!
    # Command: "/gamerule doDaylightCycle false"
    Enabled: false

  # If true, the time of the world will be based on that in real life
  #
  #            /!\ !! Warning !! /!\
  #
  # If you have a plugin that uses game time for something,
  # that setting could break that plugin!
  UseRealTime:
    # Do you want to rely on world time or real lifetime?
    # /!\ If is Enabled, we suggest disabling the doDaylightCycle rule, as to further optimize the world!
    # Command: "/gamerule doDaylightCycle false"
    Enabled: false
    # Available Time Zones https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    Timezone: "GMT+2"

  # Indicates the (real life) month number in which the plugin will have to work
  #  1 => January
  #  12 => December
  #  -1 => to work every month
  Month: -1
  # At what (world game) time does the night starts?
  #   format "hh:mm"
  Starts: "19:00"
  # At what (world game) time does the night ends?
  #   format "hh:mm"
  Ends: "05:30"
  # If true, the indicated worlds will be in blacklist
  # If false, the indicated worlds will be in whitelist
  Blacklist: false
  # List of the various worlds names
  # Set to 'ALLWORLDS' to use all worlds!
  # (NB: is cAsE sEnSiTiVe)
  List:
    - 'world'
