# 
#    |  |    \    _ \  _ \ \ \  /     \ |  __| \ \      /   \ \  /  __|    \    _ \   | 
#    __ |   _ \   __/  __/  \  /     .  |  _|   \ \ \  /     \  /   _|    _ \     /  _| 
#   _| _| _/  _\ _|   _|     _|     _|\_| ___|   \_/\_/       _|   ___| _/  _\ _|_\  _) 
# 
#  Developed by xSavior_of_God                                     
# 
#  For SUPPORT                                                      
#   <Discord/>     https://discord.gg/5UuVdTE
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

# Set it to true to enable the plugin!
Enabled: false
